### PR TITLE
add Limbo options and update skyhelper-networth

### PR DESCRIPTION
**Pull request by GeorgeFilos**
Make it go to limbo and not spam debug

### CODE REVIEW

**Comment by Kathund** [comment]
> Make it go to limbo and not spam debug

Could possibly make it an option on the config coz some people might like to see it in lobbys or something like that

**Comment by GeorgeFilos** [comment]
> > Make it go to limbo and not spam debug
> 
> Could possibly make it an option on the config coz some people might like to see it in lobbys or something like that 

Me when pimps

**Comment by GeorgeFilos** [comment]
Added configurable options for this and also updated skyhelper networth

**Review by DuckySoLucky — CHANGES_REQUESTED** [review]
very bad, gonna break production. you should quit coding this isn't for oyu

**Pull request merged**
