### PR TITLE
New Daily/Weekly/Monthly Command to track stats - New Commands

### PR DESCRIPTION
**Pull request by Kathund**
Tested and works
Needs a !register command to add your self to the data base - **!REGISTER IS COMING SOON**

### CODE REVIEW

**Comment by Kathund** [comment]
Added a register command so people can register and have them tracked

Also added a note to denick about it being patched when it dosent work

**Comment by Kathund** [comment]
removed some random dumb shit

**Comment by Kathund** [comment]
Added new Command !player (!p) and added an example command for monkeys who want to make new commands

Added start.bat what will run everything

**Comment by Kathund** [comment]
added !go - lets you look up a guild based of someones ign
added !g- lets you look up a guild based of a guild name

**Comment by Kathund** [comment]
Added a more in depth guide for monkeys

**Review by Kathund — COMMENTED** [review]
a

**Review by DuckySoLucky — CHANGES_REQUESTED** [review]
lgtm, but can you fix es-lint errors?

**Comment by Kathund** [comment]
> lgtm, but can you fix es-lint errors?

I added it to my todo list already

and I need to fix something that's causing the discord part to stop working

eg if u type in the discord channel it dosent get send to mc

**Comment by Kathund** [comment]
image
@DuckySoLucky 

EVERYTHING NEW

!daily/weekly/monthly
will show your stats in x time 
if your not in the database you can !register yourself

!go <player> can look up someones guild stats by player name
!guild <guild name> will look up a guild by a name and supports more then one word

**Pull request merged**
