### PR TITLE
Update updateCommand.js

### PR DESCRIPTION
**Pull request by Killermaschine88**
Fix duel stats not being in place and thus erroring

### CODE REVIEW

**Review by Kathund — CHANGES_REQUESTED** [review]
Can you do this for all other gamemades and also male a default value of 0 or "" (depending on the stat)

**Comment by Killermaschine88** [comment]
there haven't been issues with any others yet only duels seems to have said issue with the api

will add the default to 0 in a gew

**Comment by Kathund** [comment]
> there haven't been issues with any others yet only duels seems to have said issue with the api
> 
> will add the default to 0 in a few

In reborn source if there is no data for say bedwars it will make bedwars null. So ye its not an "issue" now but it can be

**Comment by Killermaschine88** [comment]
if it works it works your welcome to do the change yourself its annoying on phone only wanted to quickly fix said issue with duels

**Pull request merged**
