### PR TITLE
Verification

### PR DESCRIPTION
**Pull request by Kathund**
# Config options
  - Full toggle
  - Verified role 
  - Guild member role
  - auto update all users
  - interval for how often it updates everyone
  - auto unverify users who leave
  - unverified role auto given on user join
  - channel auto update logs
  - Ability to customize the verified user name
  - Ingame guild ranks get matching discord roles
  
merge #251 first so i can add support for this

# Commands
  - `/verify` - Lets you verify
  - `/unverify` - Removes your verification 
  - `/update` - Updates your roles and name
 
# Staff Commands
  - `/force-verify` - Force verify a user
  - `/force-unverify` - Remove verification from a user
  - `/force-update` - Update a user
  - `/force-update-everyone` - Update ever user in the database
  - `/linked` - Find who a user is verified as

### CODE REVIEW

**Comment by Kathund** [comment]
> this would be so sigma ngl

Please grow up. This is github not discord.

**Comment by DuckySoLucky** [comment]
> this would be so sigma ngl

on skibidi

**Comment by CatboyDark** [comment]
frfr

**Comment by Killermaschine88** [comment]
code looks like shit but might work
Review successfully

**Review by DuckySoLucky — CHANGES_REQUESTED** [review]
README is missing

**Pull request merged**
