### PR TITLE
feat(Stats Channels)

### PR DESCRIPTION
**Pull request by Kathund**
Channel names variables:
  - guildName: Name of the guild
  - guildLevel: Level of the guild
  - guildXP: Amount of the xp the guild has gotten
  - guildWeeklyXP: Amount of xp in the past week the guild has gotten
  - guildMembers: Amount of members in the guild
  - discordMembers: Amount of members in the discord
  - discordChannels: Amount of channels in the discord
  - discordChannels: Amount of roles in the discord

### CODE REVIEW

**Comment by DuckySoLucky** [comment]
> should also add docs for it to follow format
> 
> otherwise code looks fine can be merged once the requested changes are done

good job my ~~slave~~ co worker.

**Comment by Kathund** [comment]
> > should also add docs for it to follow format
> > otherwise code looks fine can be merged once the requested changes are done
> 
> good job my ~slave~ co worker.

DuckySoSlave

**Comment by Kathund** [comment]
@DuckySoLucky @Killermaschine88

**Comment by Kathund** [comment]
@Killermaschine88

**Review by Killermaschine88 — APPROVED** [review]

**Pull request merged**
